---
- name: Install packages (Debian/Ubuntu)
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  become: true
  when: ansible_os_family == "Debian"

- name: Install packages (macOS)
  homebrew:
    name: "{{ packages }}"
    state: present
  when: ansible_os_family == "Darwin"
